FROM node:22-alpine

WORKDIR /app

COPY ./client/package*.json ./client/
COPY ./server/package*.json ./server/

WORKDIR /app/client
RUN npm install

COPY ./client .
RUN npm run build

WORKDIR /app/server
RUN npm install

COPY ./server .
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
